//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BehaviorType()
        {
            this.BehaviorPerformed = new HashSet<BehaviorPerformed>();
        }
    
        public decimal behaviorID { get; set; }
        public string behaviorTitle { get; set; }
        public string behaviorDescription { get; set; }
        public Nullable<decimal> pointValue { get; set; }
        public Nullable<decimal> classID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BehaviorPerformed> BehaviorPerformed { get; set; }
        public virtual Classroom Classroom { get; set; }
    }
}
