//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BehaviorPerformed
    {
        public decimal BPID { get; set; }
        public Nullable<System.DateTime> BP_Date { get; set; }
        public Nullable<decimal> behaviorID { get; set; }
        public Nullable<decimal> studentID { get; set; }
    
        public virtual BehaviorType BehaviorType { get; set; }
        public virtual Student Student { get; set; }
    }
}
