//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomManagementApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrizeRequest
    {
        public decimal requestID { get; set; }
        public Nullable<System.DateTime> dateRequested { get; set; }
        public Nullable<System.DateTime> datefulfilled { get; set; }
        public Nullable<decimal> studentID { get; set; }
        public Nullable<decimal> prizeID { get; set; }
    
        public virtual Prize Prize { get; set; }
        public virtual Student Student { get; set; }
    }
}
